### ISSUE TITLE
how to provide custom runtime for lambda?

### ISSUE THREAD

**Issue by davidxiaobj** [Ovski4/tutorials#1]
Hello, mate
   Your tutorial is great, 
   Do you know how to provide custom runtime for lambda for `localstack`? i am trying to set up with https://github.com/hayd/deno-lambda/releases/download/1.0.2/deno-lambda-layer.zip
   I tried, it doesn't work, because the app source code and bootstrap(layer) code seems only work in separate directories( /var/task, and /opt), while there is only one zip file, it means all of these files can only be in /var/task by default.

Thanks

**Comment by Ovski4** [comment]
Hey mate,

Thanks for the feedback, that's much appreciated

I had a look at your closed issues https://github.com/lambci/docker-lambda/issues/277 and https://github.com/hayd/deno-lambda/issues/81 to understand what you mean.

It seems localstack can only use zip files that are meant to be lambda handlers (the app source code). As you say these handlers will be located in /var/task in the lambci/docker-lambda container. I found the localstack code responsible for this [here](https://github.com/localstack/localstack/blob/34daf13e8f0c883eceb3ae3f83a6ab20e8fc9460/localstack/services/awslambda/lambda_executors.py#L367).

I don't think there is currently a way to add "layer code" using localstack that would end up in /opt in the lambci/docker-lambda container.

Do I understand your issue correctly?

If I'm right and that the "<layer_dir>" volume in lambci/docker-lambda is not implemented in localstack, you might try opening an issue on the localstack repo. Ask how this volume can be configured (maybe there is a workaround, or this will require a pull request)

**Comment by davidxiaobj** [comment]
thanks very much, mate,
yes, you are right,
I reckon `localstack` will not address my concern, because layer support is part of `Pro` version

Thanks
